In [18]:
import pandas as pd
import numpy as np
import seaborn as sns

In [19]:
pokemon = pd.read_csv("pokemon.csv")
pokemon.head()

#                   Name Type 1  Type 2  Total  HP  Attack  Defense  \
0  1              Bulbasaur  Grass  Poison    318  45      49       49   
1  2                Ivysaur  Grass  Poison    405  60      62       63   
2  3               Venusaur  Grass  Poison    525  80      82       83   
3  3  VenusaurMega Venusaur  Grass  Poison    625  80     100      123   
4  4             Charmander   Fire     NaN    309  39      52       43   

   Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0       65       65     45           1      False  
1       80       80     60           1      False  
2      100      100     80           1      False  
3      122      120     80           1      False  
4       60       50     65           1      False

In [20]:
# def compute_total(pokemon):
#     if pokemon['HP']+pokemon['Attack']+pokemon['Defense']+pokemon['Sp. Atk']+pokemon['Sp. Def']+pokemon['Speed'] == pokemon['Total']:
#         return 'True'
#     else:
#         return 'False'

poke_stats = pokemon['Total'] ==  pokemon['HP']+pokemon['Attack']+pokemon['Defense']+pokemon['Sp. Atk']+pokemon['Sp. Def']+pokemon['Speed']
poke_stats
poke_stats.unique()
# pokemon_total = compute_total(pokemon)
# display(pokemon_total)

array([ True])

In [21]:
pokemon['Combo Type'] = pokemon['Type 1'] + ('-'+pokemon['Type 2'].fillna(' '))
pokemon.head(10)

#                       Name Type 1  Type 2  Total  HP  Attack  Defense  \
0  1                  Bulbasaur  Grass  Poison    318  45      49       49   
1  2                    Ivysaur  Grass  Poison    405  60      62       63   
2  3                   Venusaur  Grass  Poison    525  80      82       83   
3  3      VenusaurMega Venusaur  Grass  Poison    625  80     100      123   
4  4                 Charmander   Fire     NaN    309  39      52       43   
5  5                 Charmeleon   Fire     NaN    405  58      64       58   
6  6                  Charizard   Fire  Flying    534  78      84       78   
7  6  CharizardMega Charizard X   Fire  Dragon    634  78     130      111   
8  6  CharizardMega Charizard Y   Fire  Flying    634  78     104       78   
9  7                   Squirtle  Water     NaN    314  44      48       65   

   Sp. Atk  Sp. Def  Speed  Generation  Legendary    Combo Type  
0       65       65     45           1      False  Grass-Poison  
1       80       80     60           1      False  Grass-Poison  
2      100      100     80           1      False  Grass-Poison  
3      122      120     80           1      False  Grass-Poison  
4       60       50     65           1      False        Fire-   
5       80       65     80           1      False        Fire-   
6      109       85    100           1      False   Fire-Flying  
7      130       85    100           1      False   Fire-Dragon  
8      159      115    100           1      False   Fire-Flying  
9       50       64     43           1      False       Water-

In [22]:
pokemon['Type 2'].fillna('NA', inplace=True)
unique_poketype = list(pokemon['Type 2'].unique())
sorted(unique_poketype)

['Bug',
 'Dark',
 'Dragon',
 'Electric',
 'Fairy',
 'Fighting',
 'Fire',
 'Flying',
 'Ghost',
 'Grass',
 'Ground',
 'Ice',
 'NA',
 'Normal',
 'Poison',
 'Psychic',
 'Rock',
 'Steel',
 'Water']

In [23]:
from sklearn.preprocessing import OneHotEncoder
type1 = pokemon[['Type 1']]
print(type1)
encoder = OneHotEncoder().fit(type1)
encoded = encoder.transform(type1).toarray()
cols = encoder.get_feature_names_out()
type1_encoded = pd.DataFrame(encoded,columns=cols)
type1_encoded

      Type 1
0      Grass
1      Grass
2      Grass
3      Grass
4       Fire
..       ...
795     Rock
796     Rock
797  Psychic
798  Psychic
799     Fire

[800 rows x 1 columns]


Type 1_Bug  Type 1_Dark  Type 1_Dragon  Type 1_Electric  Type 1_Fairy  \
0           0.0          0.0            0.0              0.0           0.0   
1           0.0          0.0            0.0              0.0           0.0   
2           0.0          0.0            0.0              0.0           0.0   
3           0.0          0.0            0.0              0.0           0.0   
4           0.0          0.0            0.0              0.0           0.0   
..          ...          ...            ...              ...           ...   
795         0.0          0.0            0.0              0.0           0.0   
796         0.0          0.0            0.0              0.0           0.0   
797         0.0          0.0            0.0              0.0           0.0   
798         0.0          0.0            0.0              0.0           0.0   
799         0.0          0.0            0.0              0.0           0.0   

     Type 1_Fighting  Type 1_Fire  Type 1_Flying  Type 1_Ghost  Type 1_Grass  \
0                0.0          0.0            0.0           0.0           1.0   
1                0.0          0.0            0.0           0.0           1.0   
2                0.0          0.0            0.0           0.0           1.0   
3                0.0          0.0            0.0           0.0           1.0   
4                0.0          1.0            0.0           0.0           0.0   
..               ...          ...            ...           ...           ...   
795              0.0          0.0            0.0           0.0           0.0   
796              0.0          0.0            0.0           0.0           0.0   
797              0.0          0.0            0.0           0.0           0.0   
798              0.0          0.0            0.0           0.0           0.0   
799              0.0          1.0            0.0           0.0           0.0   

     Type 1_Ground  Type 1_Ice  Type 1_Normal  Type 1_Poison  Type 1_Psychic  \
0              0.0         0.0            0.0            0.0             0.0   
1              0.0         0.0            0.0            0.0             0.0   
2              0.0         0.0            0.0            0.0             0.0   
3              0.0         0.0            0.0            0.0             0.0   
4              0.0         0.0            0.0            0.0             0.0   
..             ...         ...            ...            ...             ...   
795            0.0         0.0            0.0            0.0             0.0   
796            0.0         0.0            0.0            0.0             0.0   
797            0.0         0.0            0.0            0.0             1.0   
798            0.0         0.0            0.0            0.0             1.0   
799            0.0         0.0            0.0            0.0             0.0   

     Type 1_Rock  Type 1_Steel  Type 1_Water  
0            0.0           0.0           0.0  
1            0.0           0.0           0.0  
2            0.0           0.0           0.0  
3            0.0           0.0           0.0  
4            0.0           0.0           0.0  
..           ...           ...           ...  
795          1.0           0.0           0.0  
796          1.0           0.0           0.0  
797          0.0           0.0           0.0  
798          0.0           0.0           0.0  
799          0.0           0.0           0.0  

[800 rows x 18 columns]

In [24]:
type2 = pokemon[['Type 2']]
encoder = OneHotEncoder().fit(type2)
encoded = encoder.transform(type2).toarray()
cols2 = encoder.get_feature_names_out()
type2_encoded = pd.DataFrame(encoded,columns=cols2)
type2_encoded = type2_encoded
type2_encoded

Type 2_Bug  Type 2_Dark  Type 2_Dragon  Type 2_Electric  Type 2_Fairy  \
0           0.0          0.0            0.0              0.0           0.0   
1           0.0          0.0            0.0              0.0           0.0   
2           0.0          0.0            0.0              0.0           0.0   
3           0.0          0.0            0.0              0.0           0.0   
4           0.0          0.0            0.0              0.0           0.0   
..          ...          ...            ...              ...           ...   
795         0.0          0.0            0.0              0.0           1.0   
796         0.0          0.0            0.0              0.0           1.0   
797         0.0          0.0            0.0              0.0           0.0   
798         0.0          1.0            0.0              0.0           0.0   
799         0.0          0.0            0.0              0.0           0.0   

     Type 2_Fighting  Type 2_Fire  Type 2_Flying  Type 2_Ghost  Type 2_Grass  \
0                0.0          0.0            0.0           0.0           0.0   
1                0.0          0.0            0.0           0.0           0.0   
2                0.0          0.0            0.0           0.0           0.0   
3                0.0          0.0            0.0           0.0           0.0   
4                0.0          0.0            0.0           0.0           0.0   
..               ...          ...            ...           ...           ...   
795              0.0          0.0            0.0           0.0           0.0   
796              0.0          0.0            0.0           0.0           0.0   
797              0.0          0.0            0.0           1.0           0.0   
798              0.0          0.0            0.0           0.0           0.0   
799              0.0          0.0            0.0           0.0           0.0   

     Type 2_Ground  Type 2_Ice  Type 2_NA  Type 2_Normal  Type 2_Poison  \
0              0.0         0.0        0.0            0.0            1.0   
1              0.0         0.0        0.0            0.0            1.0   
2              0.0         0.0        0.0            0.0            1.0   
3              0.0         0.0        0.0            0.0            1.0   
4              0.0         0.0        1.0            0.0            0.0   
..             ...         ...        ...            ...            ...   
795            0.0         0.0        0.0            0.0            0.0   
796            0.0         0.0        0.0            0.0            0.0   
797            0.0         0.0        0.0            0.0            0.0   
798            0.0         0.0        0.0            0.0            0.0   
799            0.0         0.0        0.0            0.0            0.0   

     Type 2_Psychic  Type 2_Rock  Type 2_Steel  Type 2_Water  
0               0.0          0.0           0.0           0.0  
1               0.0          0.0           0.0           0.0  
2               0.0          0.0           0.0           0.0  
3               0.0          0.0           0.0           0.0  
4               0.0          0.0           0.0           0.0  
..              ...          ...           ...           ...  
795             0.0          0.0           0.0           0.0  
796             0.0          0.0           0.0           0.0  
797             0.0          0.0           0.0           0.0  
798             0.0          0.0           0.0           0.0  
799             0.0          0.0           0.0           1.0  

[800 rows x 19 columns]

In [34]:
types_encoded = type1_encoded+type2_encoded
types_encoded

Type 1_Bug  Type 1_Dark  Type 1_Dragon  Type 1_Electric  Type 1_Fairy  \
0           NaN          NaN            NaN              NaN           NaN   
1           NaN          NaN            NaN              NaN           NaN   
2           NaN          NaN            NaN              NaN           NaN   
3           NaN          NaN            NaN              NaN           NaN   
4           NaN          NaN            NaN              NaN           NaN   
..          ...          ...            ...              ...           ...   
795         NaN          NaN            NaN              NaN           NaN   
796         NaN          NaN            NaN              NaN           NaN   
797         NaN          NaN            NaN              NaN           NaN   
798         NaN          NaN            NaN              NaN           NaN   
799         NaN          NaN            NaN              NaN           NaN   

     Type 1_Fighting  Type 1_Fire  Type 1_Flying  Type 1_Ghost  Type 1_Grass  \
0                NaN          NaN            NaN           NaN           NaN   
1                NaN          NaN            NaN           NaN           NaN   
2                NaN          NaN            NaN           NaN           NaN   
3                NaN          NaN            NaN           NaN           NaN   
4                NaN          NaN            NaN           NaN           NaN   
..               ...          ...            ...           ...           ...   
795              NaN          NaN            NaN           NaN           NaN   
796              NaN          NaN            NaN           NaN           NaN   
797              NaN          NaN            NaN           NaN           NaN   
798              NaN          NaN            NaN           NaN           NaN   
799              NaN          NaN            NaN           NaN           NaN   

     ...  Type 2_Grass  Type 2_Ground  Type 2_Ice  Type 2_NA  Type 2_Normal  \
0    ...           NaN            NaN         NaN        NaN            NaN   
1    ...           NaN            NaN         NaN        NaN            NaN   
2    ...           NaN            NaN         NaN        NaN            NaN   
3    ...           NaN            NaN         NaN        NaN            NaN   
4    ...           NaN            NaN         NaN        NaN            NaN   
..   ...           ...            ...         ...        ...            ...   
795  ...           NaN            NaN         NaN        NaN            NaN   
796  ...           NaN            NaN         NaN        NaN            NaN   
797  ...           NaN            NaN         NaN        NaN            NaN   
798  ...           NaN            NaN         NaN        NaN            NaN   
799  ...           NaN            NaN         NaN        NaN            NaN   

     Type 2_Poison  Type 2_Psychic  Type 2_Rock  Type 2_Steel  Type 2_Water  
0              NaN             NaN          NaN           NaN           NaN  
1              NaN             NaN          NaN           NaN           NaN  
2              NaN             NaN          NaN           NaN           NaN  
3              NaN             NaN          NaN           NaN           NaN  
4              NaN             NaN          NaN           NaN           NaN  
..             ...             ...          ...           ...           ...  
795            NaN             NaN          NaN           NaN           NaN  
796            NaN             NaN          NaN           NaN           NaN  
797            NaN             NaN          NaN           NaN           NaN  
798            NaN             NaN          NaN           NaN           NaN  
799            NaN             NaN          NaN           NaN           NaN  

[800 rows x 37 columns]

In [26]:
pokemon_types = pokemon.reindex(pokemon.columns.tolist() + unique_poketype, axis=1, fill_value=0)
pokemon_types

#                   Name   Type 1  Type 2  Total  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison    318  45      49       49   
1      2                Ivysaur    Grass  Poison    405  60      62       63   
2      3               Venusaur    Grass  Poison    525  80      82       83   
3      3  VenusaurMega Venusaur    Grass  Poison    625  80     100      123   
4      4             Charmander     Fire      NA    309  39      52       43   
..   ...                    ...      ...     ...    ...  ..     ...      ...   
795  719                Diancie     Rock   Fairy    600  50     100      150   
796  719    DiancieMega Diancie     Rock   Fairy    700  50     160      110   
797  720    HoopaHoopa Confined  Psychic   Ghost    600  80     110       60   
798  720     HoopaHoopa Unbound  Psychic    Dark    680  80     160       60   
799  721              Volcanion     Fire   Water    600  80     110      120   

     Sp. Atk  Sp. Def  ...  Steel  Ice  Rock Dark  Water  Electric  Fire  \
0         65       65  ...      0    0     0    0      0         0     0   
1         80       80  ...      0    0     0    0      0         0     0   
2        100      100  ...      0    0     0    0      0         0     0   
3        122      120  ...      0    0     0    0      0         0     0   
4         60       50  ...      0    0     0    0      0         0     0   
..       ...      ...  ...    ...  ...   ...  ...    ...       ...   ...   
795      100      150  ...      0    0     0    0      0         0     0   
796      160      110  ...      0    0     0    0      0         0     0   
797      150      130  ...      0    0     0    0      0         0     0   
798      170      130  ...      0    0     0    0      0         0     0   
799      130       90  ...      0    0     0    0      0         0     0   

     Ghost  Bug  Normal  
0        0    0       0  
1        0    0       0  
2        0    0       0  
3        0    0       0  
4        0    0       0  
..     ...  ...     ...  
795      0    0       0  
796      0    0       0  
797      0    0       0  
798      0    0       0  
799      0    0       0  

[800 rows x 33 columns]

In [27]:
pokemon_types.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'Total', 'HP', 'Attack', 'Defense',
       'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary', 'Combo Type',
       'Poison', 'NA', 'Flying', 'Dragon', 'Ground', 'Fairy', 'Grass',
       'Fighting', 'Psychic', 'Steel', 'Ice', 'Rock', 'Dark', 'Water',
       'Electric', 'Fire', 'Ghost', 'Bug', 'Normal'],
      dtype='object')

In [28]:
pokemon_types['Combo Type']

0       Grass-Poison
1       Grass-Poison
2       Grass-Poison
3       Grass-Poison
4             Fire- 
           ...      
795       Rock-Fairy
796       Rock-Fairy
797    Psychic-Ghost
798     Psychic-Dark
799       Fire-Water
Name: Combo Type, Length: 800, dtype: object

In [29]:
pokemon_types['Type 1'].unique()

array(['Grass', 'Fire', 'Water', 'Bug', 'Normal', 'Poison', 'Electric',
       'Ground', 'Fairy', 'Fighting', 'Psychic', 'Rock', 'Ghost', 'Ice',
       'Dragon', 'Dark', 'Steel', 'Flying'], dtype=object)

In [30]:
pokemon_types['Type 2'].unique()

array(['Poison', 'NA', 'Flying', 'Dragon', 'Ground', 'Fairy', 'Grass',
       'Fighting', 'Psychic', 'Steel', 'Ice', 'Rock', 'Dark', 'Water',
       'Electric', 'Fire', 'Ghost', 'Bug', 'Normal'], dtype=object)

In [31]:
pokemon_types['Type 1'][0]

'Grass'

In [32]:
pokemon_types['Type 2'][0]

'Poison'

In [37]:
pokemon_types.loc[pokemon_types['Type 1'] == 'Grass','Grass'] = 1
pokemon_types.loc[pokemon_types['Type 2'] == 'Grass','Grass'] = 1
display(pokemon_types['Grass'])

0      1
1      1
2      1
3      1
4      0
      ..
795    0
796    0
797    0
798    0
799    0
Name: Grass, Length: 800, dtype: int64

In [38]:
pokemon_types['Grass'].value_counts()

0    705
1     95
Name: Grass, dtype: int64

In [41]:
pokemon_types['Poison'].value_counts()

0    800
Name: Poison, dtype: int64

In [42]:
def dummy_types(df):
    for type1 in df['Type 1']:
        df.loc[df['Type 1'] == type1,str(type1)] = 1
    for type2 in df['Type 2']:
        df.loc[df['Type 2'] == type2,str(type2)] = 1
    return 

In [44]:
dummy_types(pokemon_types)
pokemon_types

#                   Name   Type 1  Type 2  Total  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison    318  45      49       49   
1      2                Ivysaur    Grass  Poison    405  60      62       63   
2      3               Venusaur    Grass  Poison    525  80      82       83   
3      3  VenusaurMega Venusaur    Grass  Poison    625  80     100      123   
4      4             Charmander     Fire      NA    309  39      52       43   
..   ...                    ...      ...     ...    ...  ..     ...      ...   
795  719                Diancie     Rock   Fairy    600  50     100      150   
796  719    DiancieMega Diancie     Rock   Fairy    700  50     160      110   
797  720    HoopaHoopa Confined  Psychic   Ghost    600  80     110       60   
798  720     HoopaHoopa Unbound  Psychic    Dark    680  80     160       60   
799  721              Volcanion     Fire   Water    600  80     110      120   

     Sp. Atk  Sp. Def  ...  Steel  Ice  Rock Dark  Water  Electric  Fire  \
0         65       65  ...      0    0     0    0      0         0     0   
1         80       80  ...      0    0     0    0      0         0     0   
2        100      100  ...      0    0     0    0      0         0     0   
3        122      120  ...      0    0     0    0      0         0     0   
4         60       50  ...      0    0     0    0      0         0     1   
..       ...      ...  ...    ...  ...   ...  ...    ...       ...   ...   
795      100      150  ...      0    0     1    0      0         0     0   
796      160      110  ...      0    0     1    0      0         0     0   
797      150      130  ...      0    0     0    0      0         0     0   
798      170      130  ...      0    0     0    1      0         0     0   
799      130       90  ...      0    0     0    0      1         0     1   

     Ghost  Bug  Normal  
0        0    0       0  
1        0    0       0  
2        0    0       0  
3        0    0       0  
4        0    0       0  
..     ...  ...     ...  
795      0    0       0  
796      0    0       0  
797      1    0       0  
798      0    0       0  
799      0    0       0  

[800 rows x 33 columns]

In [46]:
pokemon_types['Fire'].value_counts()

0    736
1     64
Name: Fire, dtype: int64

In [47]:
pokemon_types['NA'].value_counts()

0    414
1    386
Name: NA, dtype: int64

In [48]:
pokemon_types['Ground'].value_counts()

0    733
1     67
Name: Ground, dtype: int64

In [49]:
pokemon_types2 = pokemon_types.drop('NA',axis = 1)

In [50]:
pokemon_types2.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'Total', 'HP', 'Attack', 'Defense',
       'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary', 'Combo Type',
       'Poison', 'Flying', 'Dragon', 'Ground', 'Fairy', 'Grass', 'Fighting',
       'Psychic', 'Steel', 'Ice', 'Rock', 'Dark', 'Water', 'Electric', 'Fire',
       'Ghost', 'Bug', 'Normal'],
      dtype='object')

In [51]:
pokemon_types3 = pokemon_types2.drop(['Type 1','Type 2','#','Combo Type','Generation','Legendary','HP','Attack','Defense','Sp. Atk','Sp. Def','Speed'],axis = 1)
pokemon_types3.head()

Name  Total  Poison  Flying  Dragon  Ground  Fairy  Grass  \
0              Bulbasaur    318       1       0       0       0      0      1   
1                Ivysaur    405       1       0       0       0      0      1   
2               Venusaur    525       1       0       0       0      0      1   
3  VenusaurMega Venusaur    625       1       0       0       0      0      1   
4             Charmander    309       0       0       0       0      0      0   

   Fighting  Psychic  Steel  Ice  Rock  Dark  Water  Electric  Fire  Ghost  \
0         0        0      0    0     0     0      0         0     0      0   
1         0        0      0    0     0     0      0         0     0      0   
2         0        0      0    0     0     0      0         0     0      0   
3         0        0      0    0     0     0      0         0     0      0   
4         0        0      0    0     0     0      0         0     1      0   

   Bug  Normal  
0    0       0  
1    0       0  
2    0       0  
3    0       0  
4    0       0

In [52]:
pokemon = pd.read_csv('pokemon.csv')
pokemon

#                   Name   Type 1  Type 2  Total  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison    318  45      49       49   
1      2                Ivysaur    Grass  Poison    405  60      62       63   
2      3               Venusaur    Grass  Poison    525  80      82       83   
3      3  VenusaurMega Venusaur    Grass  Poison    625  80     100      123   
4      4             Charmander     Fire     NaN    309  39      52       43   
..   ...                    ...      ...     ...    ...  ..     ...      ...   
795  719                Diancie     Rock   Fairy    600  50     100      150   
796  719    DiancieMega Diancie     Rock   Fairy    700  50     160      110   
797  720    HoopaHoopa Confined  Psychic   Ghost    600  80     110       60   
798  720     HoopaHoopa Unbound  Psychic    Dark    680  80     160       60   
799  721              Volcanion     Fire   Water    600  80     110      120   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0         65       65     45           1      False  
1         80       80     60           1      False  
2        100      100     80           1      False  
3        122      120     80           1      False  
4         60       50     65           1      False  
..       ...      ...    ...         ...        ...  
795      100      150     50           6       True  
796      160      110    110           6       True  
797      150      130     70           6       True  
798      170      130     80           6       True  
799      130       90     70           6       True  

[800 rows x 13 columns]

In [53]:
pokemon_encode = pd.get_dummies(pokemon["Type 1"]) + pd.get_dummies(pokemon["Type 2"])
#pokemon_encode = pokemon_encode.drop('NA', axis=1)
pokemon_encode

Bug  Dark  Dragon  Electric  Fairy  Fighting  Fire  Flying  Ghost  Grass  \
0      0     0       0         0      0         0     0       0      0      1   
1      0     0       0         0      0         0     0       0      0      1   
2      0     0       0         0      0         0     0       0      0      1   
3      0     0       0         0      0         0     0       0      0      1   
4      0     0       0         0      0         0     1       0      0      0   
..   ...   ...     ...       ...    ...       ...   ...     ...    ...    ...   
795    0     0       0         0      1         0     0       0      0      0   
796    0     0       0         0      1         0     0       0      0      0   
797    0     0       0         0      0         0     0       0      1      0   
798    0     1       0         0      0         0     0       0      0      0   
799    0     0       0         0      0         0     1       0      0      0   

     Ground  Ice  Normal  Poison  Psychic  Rock  Steel  Water  
0         0    0       0       1        0     0      0      0  
1         0    0       0       1        0     0      0      0  
2         0    0       0       1        0     0      0      0  
3         0    0       0       1        0     0      0      0  
4         0    0       0       0        0     0      0      0  
..      ...  ...     ...     ...      ...   ...    ...    ...  
795       0    0       0       0        0     1      0      0  
796       0    0       0       0        0     1      0      0  
797       0    0       0       0        1     0      0      0  
798       0    0       0       0        1     0      0      0  
799       0    0       0       0        0     0      0      1  

[800 rows x 18 columns]

In [55]:
ohe = OneHotEncoder()
feature_arr = ohe.fit_transform(pokemon[['Type 1']]).toarray()
print(feature_arr)
feature_labels = ohe.get_feature_names_out()
feature_labels

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


array(['Type 1_Bug', 'Type 1_Dark', 'Type 1_Dragon', 'Type 1_Electric',
       'Type 1_Fairy', 'Type 1_Fighting', 'Type 1_Fire', 'Type 1_Flying',
       'Type 1_Ghost', 'Type 1_Grass', 'Type 1_Ground', 'Type 1_Ice',
       'Type 1_Normal', 'Type 1_Poison', 'Type 1_Psychic', 'Type 1_Rock',
       'Type 1_Steel', 'Type 1_Water'], dtype=object)

In [56]:
ohe1 = OneHotEncoder()
feature_arr1 = ohe1.fit_transform(pokemon[['Type 2']]).toarray()
print(feature_arr1)
feature_labels1 = ohe1.get_feature_names_out()
feature_labels1

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


array(['Type 2_Bug', 'Type 2_Dark', 'Type 2_Dragon', 'Type 2_Electric',
       'Type 2_Fairy', 'Type 2_Fighting', 'Type 2_Fire', 'Type 2_Flying',
       'Type 2_Ghost', 'Type 2_Grass', 'Type 2_Ground', 'Type 2_Ice',
       'Type 2_Normal', 'Type 2_Poison', 'Type 2_Psychic', 'Type 2_Rock',
       'Type 2_Steel', 'Type 2_Water', 'Type 2_nan'], dtype=object)

In [57]:
features = pd.DataFrame(feature_arr,columns=feature_labels)
features.columns = features.columns.str.split('_').str[1]
features

Bug  Dark  Dragon  Electric  Fairy  Fighting  Fire  Flying  Ghost  Grass  \
0    0.0   0.0     0.0       0.0    0.0       0.0   0.0     0.0    0.0    1.0   
1    0.0   0.0     0.0       0.0    0.0       0.0   0.0     0.0    0.0    1.0   
2    0.0   0.0     0.0       0.0    0.0       0.0   0.0     0.0    0.0    1.0   
3    0.0   0.0     0.0       0.0    0.0       0.0   0.0     0.0    0.0    1.0   
4    0.0   0.0     0.0       0.0    0.0       0.0   1.0     0.0    0.0    0.0   
..   ...   ...     ...       ...    ...       ...   ...     ...    ...    ...   
795  0.0   0.0     0.0       0.0    0.0       0.0   0.0     0.0    0.0    0.0   
796  0.0   0.0     0.0       0.0    0.0       0.0   0.0     0.0    0.0    0.0   
797  0.0   0.0     0.0       0.0    0.0       0.0   0.0     0.0    0.0    0.0   
798  0.0   0.0     0.0       0.0    0.0       0.0   0.0     0.0    0.0    0.0   
799  0.0   0.0     0.0       0.0    0.0       0.0   1.0     0.0    0.0    0.0   

     Ground  Ice  Normal  Poison  Psychic  Rock  Steel  Water  
0       0.0  0.0     0.0     0.0      0.0   0.0    0.0    0.0  
1       0.0  0.0     0.0     0.0      0.0   0.0    0.0    0.0  
2       0.0  0.0     0.0     0.0      0.0   0.0    0.0    0.0  
3       0.0  0.0     0.0     0.0      0.0   0.0    0.0    0.0  
4       0.0  0.0     0.0     0.0      0.0   0.0    0.0    0.0  
..      ...  ...     ...     ...      ...   ...    ...    ...  
795     0.0  0.0     0.0     0.0      0.0   1.0    0.0    0.0  
796     0.0  0.0     0.0     0.0      0.0   1.0    0.0    0.0  
797     0.0  0.0     0.0     0.0      1.0   0.0    0.0    0.0  
798     0.0  0.0     0.0     0.0      1.0   0.0    0.0    0.0  
799     0.0  0.0     0.0     0.0      0.0   0.0    0.0    0.0  

[800 rows x 18 columns]

In [59]:
# X1=pokemon['Type 1']
# X2=pokemon['Type 2']

# encoder1 = OneHotEncoder().fit(X1)
# encoder2 = OneHotEncoder().fit(X2)


# encoded1 = encoder1.transform(X1).toarray()
# encoded2 = encoder2.transform(X2).toarray()

# cols1=encoder1.get_feature_names()
# cols2=encoder2.get_feature_names()

# encoded1=pd.DataFrame(encoded1, columns = cols1)
# encoded2=pd.DataFrame(encoded2, columns = cols2)

In [60]:
features1 = pd.DataFrame(feature_arr1,columns=feature_labels1)
features1.columns = features1.columns.str.split('_').str[1]
features1.drop(columns = 'nan', axis = 1, inplace = True)
features1

Bug  Dark  Dragon  Electric  Fairy  Fighting  Fire  Flying  Ghost  Grass  \
0    0.0   0.0     0.0       0.0    0.0       0.0   0.0     0.0    0.0    0.0   
1    0.0   0.0     0.0       0.0    0.0       0.0   0.0     0.0    0.0    0.0   
2    0.0   0.0     0.0       0.0    0.0       0.0   0.0     0.0    0.0    0.0   
3    0.0   0.0     0.0       0.0    0.0       0.0   0.0     0.0    0.0    0.0   
4    0.0   0.0     0.0       0.0    0.0       0.0   0.0     0.0    0.0    0.0   
..   ...   ...     ...       ...    ...       ...   ...     ...    ...    ...   
795  0.0   0.0     0.0       0.0    1.0       0.0   0.0     0.0    0.0    0.0   
796  0.0   0.0     0.0       0.0    1.0       0.0   0.0     0.0    0.0    0.0   
797  0.0   0.0     0.0       0.0    0.0       0.0   0.0     0.0    1.0    0.0   
798  0.0   1.0     0.0       0.0    0.0       0.0   0.0     0.0    0.0    0.0   
799  0.0   0.0     0.0       0.0    0.0       0.0   0.0     0.0    0.0    0.0   

     Ground  Ice  Normal  Poison  Psychic  Rock  Steel  Water  
0       0.0  0.0     0.0     1.0      0.0   0.0    0.0    0.0  
1       0.0  0.0     0.0     1.0      0.0   0.0    0.0    0.0  
2       0.0  0.0     0.0     1.0      0.0   0.0    0.0    0.0  
3       0.0  0.0     0.0     1.0      0.0   0.0    0.0    0.0  
4       0.0  0.0     0.0     0.0      0.0   0.0    0.0    0.0  
..      ...  ...     ...     ...      ...   ...    ...    ...  
795     0.0  0.0     0.0     0.0      0.0   0.0    0.0    0.0  
796     0.0  0.0     0.0     0.0      0.0   0.0    0.0    0.0  
797     0.0  0.0     0.0     0.0      0.0   0.0    0.0    0.0  
798     0.0  0.0     0.0     0.0      0.0   0.0    0.0    0.0  
799     0.0  0.0     0.0     0.0      0.0   0.0    0.0    1.0  

[800 rows x 18 columns]

In [61]:
one_hot_encoded = features + features1
one_hot_encoded

Bug  Dark  Dragon  Electric  Fairy  Fighting  Fire  Flying  Ghost  Grass  \
0    0.0   0.0     0.0       0.0    0.0       0.0   0.0     0.0    0.0    1.0   
1    0.0   0.0     0.0       0.0    0.0       0.0   0.0     0.0    0.0    1.0   
2    0.0   0.0     0.0       0.0    0.0       0.0   0.0     0.0    0.0    1.0   
3    0.0   0.0     0.0       0.0    0.0       0.0   0.0     0.0    0.0    1.0   
4    0.0   0.0     0.0       0.0    0.0       0.0   1.0     0.0    0.0    0.0   
..   ...   ...     ...       ...    ...       ...   ...     ...    ...    ...   
795  0.0   0.0     0.0       0.0    1.0       0.0   0.0     0.0    0.0    0.0   
796  0.0   0.0     0.0       0.0    1.0       0.0   0.0     0.0    0.0    0.0   
797  0.0   0.0     0.0       0.0    0.0       0.0   0.0     0.0    1.0    0.0   
798  0.0   1.0     0.0       0.0    0.0       0.0   0.0     0.0    0.0    0.0   
799  0.0   0.0     0.0       0.0    0.0       0.0   1.0     0.0    0.0    0.0   

     Ground  Ice  Normal  Poison  Psychic  Rock  Steel  Water  
0       0.0  0.0     0.0     1.0      0.0   0.0    0.0    0.0  
1       0.0  0.0     0.0     1.0      0.0   0.0    0.0    0.0  
2       0.0  0.0     0.0     1.0      0.0   0.0    0.0    0.0  
3       0.0  0.0     0.0     1.0      0.0   0.0    0.0    0.0  
4       0.0  0.0     0.0     0.0      0.0   0.0    0.0    0.0  
..      ...  ...     ...     ...      ...   ...    ...    ...  
795     0.0  0.0     0.0     0.0      0.0   1.0    0.0    0.0  
796     0.0  0.0     0.0     0.0      0.0   1.0    0.0    0.0  
797     0.0  0.0     0.0     0.0      1.0   0.0    0.0    0.0  
798     0.0  0.0     0.0     0.0      1.0   0.0    0.0    0.0  
799     0.0  0.0     0.0     0.0      0.0   0.0    0.0    1.0  

[800 rows x 18 columns]

In [63]:
# your code here
corr = pokemon_types3.corr()
corr
#Dragon , Psychic
pokemon_best = corr.sort_values(by = 'Total', ascending=False)

pokemon_best['Total']

C:\Users\harri\AppData\Local\Temp\ipykernel_15280\2698032133.py:2: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  corr = pokemon_types3.corr()


Total       1.000000
Dragon      0.229705
Psychic     0.124688
Steel       0.109703
Fire        0.078726
Fighting    0.077786
Ice         0.060248
Flying      0.059383
Dark        0.056154
Rock        0.032731
Electric    0.020971
Ground      0.015060
Ghost       0.003641
Water      -0.021665
Fairy      -0.036698
Grass      -0.052592
Poison     -0.090441
Normal     -0.105331
Bug        -0.145781
Name: Total, dtype: float64

In [65]:
grouped_max = pokemon_types2.groupby(['Type 1','Type 2']).agg({'Total':'max'})
grouped_max.reset_index()

Type 1    Type 2  Total
0      Bug  Electric    472
1      Bug  Fighting    600
2      Bug      Fire    550
3      Bug    Flying    600
4      Bug     Ghost    236
..     ...       ...    ...
149  Water        NA    770
150  Water    Poison    515
151  Water   Psychic    590
152  Water      Rock    495
153  Water     Steel    530

[154 rows x 3 columns]

In [66]:
best2_pokemon=grouped_max.sort_values(by=['Total'], ascending=False)
best2_pokemon.head()

Total
Type 1  Type 2         
Psychic NA          780
Dragon  Flying      780
Psychic Fighting    780
Ground  Fire        770
Water   NA          770

In [68]:
pokemon[((pokemon['Type 1'] == 'Psychic') & (pokemon['Total']== 780)) |
        ((pokemon['Type 1'] == 'Dragon') & (pokemon['Total']== 780))] 

#                   Name   Type 1    Type 2  Total   HP  Attack  \
163  150    MewtwoMega Mewtwo X  Psychic  Fighting    780  106     190   
164  150    MewtwoMega Mewtwo Y  Psychic       NaN    780  106     150   
426  384  RayquazaMega Rayquaza   Dragon    Flying    780  105     180   

     Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendary  
163      100      154      100    130           1       True  
164       70      194      120    140           1       True  
426      100      180      100    115           3       True

In [69]:
pokemon[(pokemon['Type 1']=='Dragon') & (pokemon['Type 2']=='Flying')]

#                     Name  Type 1  Type 2  Total   HP  Attack  \
161  149                Dragonite  Dragon  Flying    600   91     134   
365  334                  Altaria  Dragon  Flying    490   75      70   
408  373                Salamence  Dragon  Flying    600   95     135   
409  373  SalamenceMega Salamence  Dragon  Flying    700   95     145   
425  384                 Rayquaza  Dragon  Flying    680  105     150   
426  384    RayquazaMega Rayquaza  Dragon  Flying    780  105     180   

     Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendary  
161       95      100      100     80           1      False  
365       90       70      105     80           3      False  
408       80      110       80    100           3      False  
409      130      120       90    120           3      False  
425       90      150       90     95           3       True  
426      100      180      100    115           3       True

In [33]:
from sklearn.preprocessing import OneHotEncoder
#encoder = OneHotEncoder().
encoder = OneHotEncoder(['Type 1'])
print(encoder)
# encoded = encoder.transform(X_cat).toarray()
# print(encoded)
# #onehot_encoded = pd.DataFrame(encoded,columns=['Female', 'Male','U'])
# onehot_encoded = pd.pokemon(encoded,columns=['Type 1', 'Type 2'])
# onehot_encoded.head(20)

TypeError: OneHotEncoder.__init__() takes 1 positional argument but 2 were given

In [ ]:
#label encoding keeps just one column and makes it numerical, but watch out: you may be introducing unintended semantics
#if you want to control which number gets assigned to which category, you can use OrdinalEncoder
from sklearn.preprocessing import LabelEncoder
label_encoded = LabelEncoder().fit(X_cat).transform(X_cat) # ordered wrt value counts
label_encoded = pd.DataFrame(label_encoded,columns=X_cat.columns)
display(label_encoded.head(20))
label_encoded['gender'].value_counts()